# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lrgOiBTBpXDEx7LgY6aby_UjSa2kfPNW
"""

# List
mylist=[10,"Ram",True,123,"Things"]
print('The values are',mylist)
print(mylist[0])
print(mylist[1])
print(mylist[2])
print(mylist[3])
print(mylist[4])

mylist[-4]=False
print('After updating the value is',mylist)

mylist.append(80)
print("after appending the values are",mylist)

mylist.insert(3,10)
print("The values are",mylist)

del mylist[-2]
print("The values are",mylist)

print(type(mylist))
print(len(mylist))

a=[6,12]
b=int(input("Enter the value"))

a.insert(2,b)
print(a)

a.append(-2)
print(a)

r=[4.5,20,36]
print(r)

del r[1]
print(r)
print(type(r))

#Tuple
mytuple=(20,"No",1.7,"Sort")
print(mytuple)

mytuple=(34,56,"Bannu")
print(mytuple)

# Dictionary

mydic={"Username":"Ram","Password":9704,"Dept":"CSE"}
print(mydic)

mydic["Dept"]="CSE-AI"
print(mydic)

mydic["DOB"]=2003
print(mydic)

mydic["Brand"]=["a","b","c"]
print(mydic)

mydic.pop("Brand")
print(mydic)

del mydic

mydic={"Game":"Cricket","Name":"Sai","Age":24}
print(mydic)

mydic["Name"]="Sai Krishna"
print(mydic)

mydic["DOB"]=2004
print(mydic)

mydic["Team"]=["India"]
print(mydic)

mydic.pop("Age")
print(mydic)

del mydic

# Set
set1={1,2,3,54,5,4,5,10}
print("The values of set1 is",set1)

set1.add(30)
print(set1)

set2={"Ram",12,45,87}
print(set2)

set3=set1.union(set2)
print(set3)

set4=set1.intersection(set3)
print(set4)

set4.clear()
print(set4)

set5={20,35,68,True}
print("The values of set1 is",set1)

set5.add(75)
print(set5)

set6={"Prasad",18,42,96}
print(set6)

set7=set6.union(set5)
print(set7)

set8=set7.intersection(set6)
print(set8)

set5.clear()
print(set5)

myfile = open("a.txt","r")
print(myfile.read())

myfile=open("a.txt","w")
myfile.write("This is written by the user \n")

mylines=["Good evening \n","Welcome back to the class"]

with open("a.txt","w") as file:
  file.writelines(mylines)

#calculator
print("select a method to perform:")
print("1.add")
print("2.sub")
print("3.mul")
print("4.div")
method = input()
if method =='1':
  num1=int(input("enter your first number:"))
  num2=int(input("enter your second number:"))
  result=num1+num2
  print("the sum of two numbers is:",result)
elif method=='2':
  num1=int(input("enter your first number:"))
  num2=int(input("enter your second number:"))
  result=num1-num2
  print("the sub of two numbers is:",result)
elif method == '3':
  num1=int(input("enter your first number:"))
  num2=int(input("enter your second number:"))
  result=num1*num2
  print(result)
  print("the mul of two numbers is:",result)
elif method =='4':
  num1=int(input("enter your first number:"))
  num2=int(input("enter your second number:"))
  result=num1/num2
  print("the div of two numbers is:",result)
else:
  print("please choose any method")
file=open("calculator.txt","w")
file.write(str(result))
file.close()